name: 2 Analysis and rendering (geodienste.ch)

on:
  schedule:
  - cron:  '0 2 * * MON'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Update
        run: sudo apt-get update
        
      - name: Install libcurl
        run: sudo apt-get install -y libcurl4-openssl-dev
        
      - name: Install libudunits2 (for {units} in R)
        run: sudo apt-get install libudunits2-dev
        
      - name: Install gdal
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install gdal-bin
          sudo apt-cache madison libproj
          sudo apt-get install libgdal-dev libgeos-dev libproj-dev libsqlite0-dev
          
      - name: Install libraries
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      - name: Push contents of _site folder to repo
        uses: github-actions-x/commit@v2.9
        with:
          push-branch: 'main'
          commit-message: 'Render'
          force-add: 'true'
          files: _site/ 
          name: autoupdate
      
      #- name: Copy To Branches Action
      #  uses: planetoftheweb/copy-to-branches@v1.3
      #  env:
      #    key: gh-pages
      #    branches: main
      #    files: index.html index_files/*
      
